# Generated by Django 4.1 on 2022-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_brands", "0004_brand_flow_device_code"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE authentik_tenants_tenant RENAME TO authentik_brands_brand;
            """,
        ),
    ]
